import { Order, Product } from '@/types';

// Mock Products
export const mockProducts: Product[] = [
  {
    product_id: 'P001',
    product_name: 'Brake Pad Set',
    product_code: 'BP-2024-001',
    description: 'Premium ceramic brake pads',
    make: 'Toyota',
    model: 'Camry',
    year: '2020-2024',
  },
  {
    product_id: 'P002',
    product_name: 'Oil Filter',
    product_code: 'OF-2024-002',
    description: 'High-efficiency oil filter',
    make: 'Honda',
    model: 'Accord',
    year: '2018-2024',
  },
  {
    product_id: 'P003',
    product_name: 'Air Filter',
    product_code: 'AF-2024-003',
    description: 'HEPA cabin air filter',
    make: 'Ford',
    model: 'F-150',
    year: '2019-2024',
  },
  {
    product_id: 'P004',
    product_name: 'Spark Plug Set',
    product_code: 'SP-2024-004',
    description: 'Iridium spark plugs (set of 4)',
    make: 'Chevrolet',
    model: 'Silverado',
    year: '2020-2024',
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    order_id: 'ORD-2024-001',
    org_id: 'ORG001',
    user_id: 'USR001',
    customer_name: 'John Smith',
    customer_email: 'john.smith@email.com',
    customer_phone: '555-0101',
    total_amount: 299.99,
    discounted_amount: 279.99,
    shipping_address: '123 Main St, Springfield, IL 62701',
    sales_agent: 'Agent Mike',
    order_status: 'created',
    products: [
      {
        product_id: 'P001',
        product_name: 'Brake Pad Set',
        product_code: 'BP-2024-001',
        make: 'Toyota',
        model: 'Camry',
        year: '2020',
        quantity: 1,
        price: 299.99,
      },
    ],
    created_at: '2024-01-15T10:30:00Z',
  },
  {
    order_id: 'ORD-2024-002',
    org_id: 'ORG001',
    user_id: 'USR002',
    customer_name: 'Sarah Johnson',
    customer_email: 'sarah.j@email.com',
    customer_phone: '555-0102',
    total_amount: 89.99,
    shipping_address: '456 Oak Ave, Chicago, IL 60601',
    sales_agent: 'Agent Mike',
    order_status: 'paid',
    products: [
      {
        product_id: 'P002',
        product_name: 'Oil Filter',
        product_code: 'OF-2024-002',
        make: 'Honda',
        model: 'Accord',
        year: '2022',
        quantity: 2,
        price: 44.99,
      },
    ],
    created_at: '2024-01-14T14:20:00Z',
  },
  {
    order_id: 'ORD-2024-003',
    org_id: 'ORG001',
    user_id: 'USR003',
    customer_name: 'Michael Brown',
    customer_email: 'mbrown@email.com',
    customer_phone: '555-0103',
    total_amount: 450.00,
    shipping_address: '789 Pine Rd, Austin, TX 78701',
    sales_agent: 'Agent Sarah',
    order_status: 'processing',
    products: [
      {
        product_id: 'P001',
        product_name: 'Brake Pad Set',
        product_code: 'BP-2024-001',
        make: 'Toyota',
        model: 'Camry',
        year: '2023',
        quantity: 1,
        price: 299.99,
      },
      {
        product_id: 'P004',
        product_name: 'Spark Plug Set',
        product_code: 'SP-2024-004',
        make: 'Chevrolet',
        model: 'Silverado',
        year: '2021',
        quantity: 1,
        price: 150.00,
      },
    ],
    created_at: '2024-01-13T09:15:00Z',
  },
  {
    order_id: 'ORD-2024-004',
    org_id: 'ORG001',
    user_id: 'USR004',
    customer_name: 'Emily Davis',
    customer_email: 'emily.d@email.com',
    customer_phone: '555-0104',
    total_amount: 65.99,
    shipping_address: '321 Elm St, Seattle, WA 98101',
    sales_agent: 'Agent Mike',
    order_status: 'shipped',
    products: [
      {
        product_id: 'P003',
        product_name: 'Air Filter',
        product_code: 'AF-2024-003',
        make: 'Ford',
        model: 'F-150',
        year: '2021',
        quantity: 1,
        price: 65.99,
      },
    ],
    created_at: '2024-01-12T16:45:00Z',
  },
];
